js:
	js javascript.js

python:
	python python.py

java:
	javac Java.java && java Java

vb:
	vbnc test.vb && mono test.exe

mono-basic:
	git clone git@github.com:mono/mono-basic.git
	cd mono-basic
	./configure
	make && sudo make install

install:
	brew install mono spidermonkey

clean:
	rm *.class
	rm *.exe
	rm *.pyc
