test: python vb php javascript java

javascript:
	js javascript.js

python:
	python python.py

java:
	javac Java.java && java Java

vb:
	vbnc vb.vb && mono vb.exe

php:
	php php.php

mono-basic:
	git clone git@github.com:mono/mono-basic.git
	cd mono-basic
	./configure
	make && sudo make install

install:
	brew install mono spidermonkey

clean:
	rm *.class
	rm *.exe
	rm *.pyc
