<html>
<head>
    <title>${project} Application</title>
</head>
  <body>
     <h1 class="title">Welcome to <code>${one}</code>, an
      application generated by the <a
      href="http://docs.pylonsproject.org/projects/pyramid/current/"
     >pyramid</a> web application framework.</h1>
  </body>
</html>